apiVersion: v1
kind: ReplicationController
metadata:
  name: lasya-rc
spec:
  replicas: 6
  selector:
    app: lasyapod
  template:
    metadata:
      labels:
        app: lasyapod
    spec:
      containers:
        - name: mycontainer
          image: nginx
          ports:
            - containerPort: 80
