apiVersion: v1
kind: ReplicationController
metadata:
  name: lasya-rc
spec:
  replicas: 2
  selector:
    app: lasyapod
    version: 2.6.1
  template:
    metadata:
      labels:
        app: lasyapod
        version: 2.6.1
    spec:
      containers:
        - name: veeranjaneyulupagant/veeranjaneyulupagant180922
          image: nginx
          ports:
            - containerPort: 8080
