apiVersion: v1
kind: Service
metadata:
   name: lasya-service
   labels:
     app: lasyapod
     version: 2.6.1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
     app: lasyapod
     version: 2.6.1