apiVersion: v1
kind: Service
metadata:
   name: lasya-service
   labels:
     app: lasyapod
     version: 2.6.2
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30005
    protocol: TCP
  selector:
     app: lasyapod 
     version: 2.6.2
    
