apiVersion: v1
kind: Service
metadata:
   name: lasya-service
   labels:
     app: myjavaapp
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30005
    protocol: TCP
  selector:
     app: myjavaapp
     